[project]
name = "qt-components"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "pyserial>=3.5",
    "pyside6>=6.9.2",
]
